version: '3'

services:
  web:
    image: 314503617348.dkr.ecr.ap-southeast-1.amazonaws.com/simplejavamaven
    ports:
      - "8082:8080"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example